import { Card, CardContent, CardHeader, CardTitle } from './ui/Card';
import { Button } from './ui/Button';
import { Badge } from './ui/Badge';
import { FileText, Download, Clock, User } from 'lucide-react';

interface MedicalReportProps {
  report: any;
}

export default function MedicalReport({ report }: MedicalReportProps) {
  if (!report) return null;

  const { executive_summary, full_report, action_items } = report;

  const downloadReport = () => {
    const reportText = `
MEDICAL REPORT
==============

${executive_summary}

DETAILED FINDINGS
=================

${full_report.clinical_information}

${full_report.technique}

${full_report.findings}

${full_report.impression}

${full_report.recommendations}

ACTION ITEMS
============

${action_items?.map((item: any, idx: number) => 
  `${idx + 1}. [${item.priority}] ${item.action} (${item.timeline}) - ${item.responsible}`
).join('\n')}

Generated by MediMind BTIS v1.0
    `;

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `brain-tumor-report-${new Date().toISOString()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <FileText className="h-6 w-6 text-primary" />
          <h2 className="text-2xl font-bold">Medical Report</h2>
        </div>
        <Button onClick={downloadReport} variant="outline">
          <Download className="mr-2 h-4 w-4" />
          Download Report
        </Button>
      </div>

      {/* Executive Summary */}
      {executive_summary && (
        <Card className="border-l-4 border-l-primary">
          <CardHeader>
            <CardTitle>Executive Summary</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="prose prose-sm max-w-none dark:prose-invert">
              <p className="text-foreground whitespace-pre-wrap">{executive_summary}</p>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Full Report Sections */}
      {full_report && (
        <>
          {full_report.clinical_information && (
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Clinical Information</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-foreground whitespace-pre-wrap">{full_report.clinical_information}</p>
              </CardContent>
            </Card>
          )}

          {full_report.technique && (
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Imaging Technique</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-foreground whitespace-pre-wrap">{full_report.technique}</p>
              </CardContent>
            </Card>
          )}

          {full_report.findings && (
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Findings</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-foreground whitespace-pre-wrap">{full_report.findings}</p>
              </CardContent>
            </Card>
          )}

          {full_report.impression && (
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Impression</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-foreground whitespace-pre-wrap font-medium">{full_report.impression}</p>
              </CardContent>
            </Card>
          )}

          {full_report.recommendations && (
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Recommendations</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-foreground whitespace-pre-wrap">{full_report.recommendations}</p>
              </CardContent>
            </Card>
          )}
        </>
      )}

      {/* Action Items */}
      {action_items && action_items.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Action Items</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {action_items.map((item: any, idx: number) => (
              <div key={idx} className="border border-border rounded-md p-4 space-y-2">
                <div className="flex items-start justify-between">
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-2">
                      <Badge variant={
                        item.priority === 'high' || item.priority === 'urgent' ? 'destructive' :
                        item.priority === 'medium' ? 'default' :
                        'secondary'
                      }>
                        {item.priority}
                      </Badge>
                      <span className="text-xs text-muted-foreground">#{idx + 1}</span>
                    </div>
                    <p className="text-sm font-medium">{item.action}</p>
                  </div>
                </div>
                <div className="flex items-center gap-4 text-xs text-muted-foreground">
                  {item.timeline && (
                    <div className="flex items-center gap-1">
                      <Clock className="h-3 w-3" />
                      <span>{item.timeline}</span>
                    </div>
                  )}
                  {item.responsible && (
                    <div className="flex items-center gap-1">
                      <User className="h-3 w-3" />
                      <span>{item.responsible}</span>
                    </div>
                  )}
                </div>
              </div>
            ))}
          </CardContent>
        </Card>
      )}

      {/* Footer */}
      <Card className="bg-muted/50">
        <CardContent className="pt-6">
          <p className="text-xs text-muted-foreground text-center">
            Generated by MediMind Brain Tumor Intelligence System v1.0
          </p>
          <p className="text-xs text-muted-foreground text-center mt-1">
            {new Date().toLocaleString()}
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
