interface MedicalReportProps {
  report: any;
}

export default function MedicalReport({ report }: MedicalReportProps) {
  if (!report) return null;

  const { executive_summary, full_report, action_items } = report;

  const downloadReport = () => {
    const reportText = `
MEDICAL REPORT
==============

${executive_summary}

DETAILED FINDINGS
=================

${full_report.clinical_information}

${full_report.technique}

${full_report.findings}

${full_report.impression}

${full_report.recommendations}

ACTION ITEMS
============

${action_items?.map((item: any, idx: number) => 
  `${idx + 1}. [${item.priority}] ${item.action} (${item.timeline}) - ${item.responsible}`
).join('\n')}

Generated by MediMind BTIS v1.0
    `;

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `brain-tumor-report-${new Date().toISOString()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="medical-report">
      <div className="report-header">
        <h2>📋 Medical Report</h2>
        <button onClick={downloadReport} className="download-btn">
          ⬇️ Download Report
        </button>
      </div>

      {executive_summary && (
        <div className="report-section">
          <h3>Executive Summary</h3>
          <pre className="report-text">{executive_summary}</pre>
        </div>
      )}

      {full_report && (
        <>
          <div className="report-section">
            <h3>Clinical Information</h3>
            <pre className="report-text">{full_report.clinical_information}</pre>
          </div>

          <div className="report-section">
            <h3>Imaging Technique</h3>
            <pre className="report-text">{full_report.technique}</pre>
          </div>

          <div className="report-section">
            <h3>Findings</h3>
            <pre className="report-text">{full_report.findings}</pre>
          </div>

          <div className="report-section highlight">
            <h3>Impression</h3>
            <pre className="report-text">{full_report.impression}</pre>
          </div>

          <div className="report-section">
            <h3>Recommendations</h3>
            <pre className="report-text">{full_report.recommendations}</pre>
          </div>
        </>
      )}

      {action_items && action_items.length > 0 && (
        <div className="report-section">
          <h3>Action Items</h3>
          <div className="action-items-list">
            {action_items.map((item: any, idx: number) => (
              <div key={idx} className={`action-item priority-${item.priority?.toLowerCase()}`}>
                <div className="action-header">
                  <span className={`priority-badge ${item.priority?.toLowerCase()}`}>
                    {item.priority}
                  </span>
                  <h4>{item.action}</h4>
                </div>
                <div className="action-details">
                  <span><strong>Timeline:</strong> {item.timeline}</span>
                  <span><strong>Responsible:</strong> {item.responsible}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
